dist: xenial
language: python
python:
  - "3.7"
install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyqt5
  - pip install --upgrade pip setuptools
  - python setup.py install
script:
  - pytest -vv
